# Generated by Django 3.2.10 on 2021-12-12 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Parkplatzname')),
                ('valid_from', models.DateField(help_text='Ab wann steht der Mietvertrag grundsätzlich zur Verfügung? (TT.MM.JJJJ)', verbose_name='Start Mietvertrag')),
                ('valid_to', models.DateField(help_text='Bis wann steht der Parkplatz grundsätzlich zur Verfügung? (TT.MM.JJJJ)', verbose_name='Ende Mietvertrag')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Besitzer')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('USED_OWNER', 'USED_BY_OWNER'), ('FREE', 'FREE'), ('USED_USER', 'BOOKED_BY_USER')], max_length=10)),
                ('date', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parking_space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_spaces.parkingspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
