# Generated by Django 3.2.9 on 2021-11-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpaceEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=20, null=True)),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_spaces.parkingspace')),
            ],
        ),
    ]
