# Generated by Django 3.2.10 on 2021-12-28 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking_spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringFreeingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.BooleanField(default=False, verbose_name='Montag')),
                ('tue', models.BooleanField(default=False, verbose_name='Dienstag')),
                ('wed', models.BooleanField(default=False, verbose_name='Mittwoch')),
                ('thu', models.BooleanField(default=False, verbose_name='Donnerstag')),
                ('fri', models.BooleanField(default=False, verbose_name='Freitag')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
