# Generated by Django 3.2.10 on 2022-01-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0002_recurringfreeingevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringfreeingevents',
            name='user',
        ),
        migrations.AddField(
            model_name='recurringfreeingevents',
            name='parking_space_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parking_spaces.parkingspace'),
            preserve_default=False,
        ),
    ]
