# Generated by Django 3.2.9 on 2021-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0003_auto_20211106_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspaceevent',
            name='week_of_date',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingspaceevent',
            name='user',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
