# Generated by Django 3.2.10 on 2022-01-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0003_auto_20220103_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspaceevent',
            old_name='parking_space_id',
            new_name='parking_space',
        ),
        migrations.RenameField(
            model_name='recurringfreeingevents',
            old_name='parking_space_id',
            new_name='parking_space',
        ),
    ]
