# Generated by Django 3.2.9 on 2021-11-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0004_auto_20211106_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspaceevent',
            name='week_of_date',
        ),
    ]
