# Generated by Django 3.2.9 on 2021-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0005_remove_parkingspaceevent_week_of_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspaceevent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
