# Generated by Django 3.2.9 on 2021-11-13 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0006_parkingspaceevent_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parkingspaceevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspaceevent',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
