# Generated by Django 3.2.9 on 2021-12-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spaces', '0010_alter_parkingspace_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspaceevent',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
