# Generated by Django 3.2.10 on 2021-12-12 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking_spaces', '0011_alter_parkingspaceevent_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspaceevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
